=== angeloelrincon/actividad_9/actividad_9.dtd
<!ELEMENT classroom (teachers, students)>
<!ELEMENT teachers (teacher+)>
<!ELEMENT teacher (teacher_name, teacher_modules)>
<!ELEMENT teacher_name (#PCDATA)>
<!ELEMENT teacher_modules (teacher_module+)>
<!ELEMENT teacher_module (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (student_name, student_modules)>
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT student_modules (student_module+)>
<!ELEMENT student_module (#PCDATA)>

=== angeloelrincon/actividad_9/actividad_9.xml
<!DOCTYPE classroom SYSTEM "actividad_9.dtd">

<classroom>
    <teachers>
        <teacher>
            <teacher_name>Tiburcio</teacher_name>
            <teacher_modules>
                <teacher_module>LND</teacher_module>
            </teacher_modules>
        </teacher>
        <teacher>
            <teacher_name>Pino</teacher_name>
            <teacher_modules>
                <teacher_module>SSF</teacher_module>
                <teacher_module>DJK</teacher_module>
            </teacher_modules>
        </teacher>
        <teacher>
            <teacher_name>Mirian</teacher_name>
            <teacher_modules>
                <teacher_module>PRO</teacher_module>
            </teacher_modules>
        </teacher>
    </teachers>
    <students>
        <student>
            <student_name>Angelo</student_name>
            <student_modules>
                <student_module>PRO</student_module>
                <student_module>ETS</student_module>
                <student_module>IKL</student_module>
                <student_module>ITK</student_module>
                <student_module>LND</student_module>
                <student_module>BAE</student_module>
                <student_module>SSF</student_module>
                <student_module>DJK</student_module>
            </student_modules>
        </student>
        <student>
            <student_name>Carlos</student_name>
            <student_modules>
                <student_module>PRO</student_module>
                <student_module>ETS</student_module>
                <student_module>IKL</student_module>
                <student_module>ITK</student_module>
                <student_module>LND</student_module>
                <student_module>BAE</student_module>
                <student_module>SSF</student_module>
                <student_module>DJK</student_module>
            </student_modules>
        </student> 
        <student>
            <student_name>Pepe</student_name>
            <student_modules>
                <student_module>PRO</student_module>
            </student_modules>
        </student>
    </students>
</classroom>
